// <auto-generated />
namespace AdvertProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class forbiden_words : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forbiden_words));
        
        string IMigrationMetadata.Id
        {
            get { return "202212181331302_forbiden_words"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
